apiVersion: v1
kind: Service
metadata:
  name: service-postgresql  
  namespace: odoo-namespace
spec:
  selector:
    name: postgresql # wskazanie na nazwę podów jakie service ma udostępniać
  ports:
    - port: 5432  # port na zewnątrz na jakim będzie udostępniony
      targetPort: 5432   # port kontenera
      protocol: TCP
  type: ClusterIP  # typ serwisu. Domyślny typ (ClusterIP) czyli udostępnienie aplikacji tylko w obrębie klastra.
